version: "3"

services:

  backend:
    build: ./backend
    command: gunicorn app:app -w 2 --threads 2 -b 0.0.0.0:8000
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    command: npm run start
    env_file:
      ./frontend/.env
    ports:
      - "3000:3000"
  